Sprint 1/step 2
Yodiculta/react-burger pull request #2
Opened 2022-01-15 18:59 UTC by Yodiculta

I have changed all components on functional and add "Esc" to close overlay

2022-01-15 22:26 UTC, grishbar requested changes
Молодец, большая работа проделана, круто, что везде все написано на функциональных компонентах, и берешь пропсы компонента при помощи деструктуризации, это очень хорошая практика, старайся придерживаться ей всегда. 

Есть некоторые моменты, которые нужно исправить для принятия работы:

- [ ] Все компоненты должны быть с расширение .jsx и названы в kebab-case
- [ ] Разделить Стейт компонентов, на более примитивные объекты
- [ ] Вынести константные переменные из компонентов,  и назвать их в SNAKE_CASE
- [ ] Избавиться от создания функций в jsx
- [ ] Переделать обработку закрытия модалки по клавише escape, должно быть сделано при помощи useEffect
- [ ] Избавиться от онлайновых стилей
- [ ] Убрать взаимодействие с DOM (переделать компонент модалки)

2022-01-15 22:26 UTC, grishbar commented on src/components/app/App.tsx
> +      })
`надо исправить`
такие состояния компонента нужно разделять, во первых это разные абстракции поэтому семантически так будет более корректно, во вторых если у тебя будет меняться хоть одно из этих полей, то будет перерендываться все поля с ними связанными а не только измененные, что не очень, теряешь в производительности, также манипулировать с разделенными примитивными объектами намного проще, чем с большим сложным объектом
https://reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables

2022-01-15 22:26 UTC, grishbar commented on src/components/app/App.tsx
> +   const url="https://norma.nomoreparties.space/api/ingredients"
`надо исправить`
Имя переменной url слишком абстрактное, оно не несет особого смысла, и такие константые переменные принято выносить из компонента, еще лучше в отдельный файл и называть в SNAKE_CASE, что позволяет сразу понять, что эта переменная константна и менять ее не надо

2022-01-15 22:26 UTC, grishbar commented on src/components/app/App.tsx
> +      }, [])
`надо исправить`
При совершении запроса, он может успешно выполнится и вернуться не с 2xx статусом и соответственно он будет содержать не данные для ингредиентов, и не совсем очевидно, но такой запрос не попадет в блок catch, только если у тебя не случится какая то скриптовая ошибка тут, например  в json не полчится преобразовать, только тогда ты попадешь в catch. Соответственно тебе тут нужно если не [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) выкидывать ошибку, тогда тебя перекинет в блок catch
Также надо удалить console.log

2022-01-15 22:26 UTC, grishbar commented on src/components/app/App.tsx
> +         </div>
`надо исправить`
в твоем коде не должно быть таких абстрактных переменных, как data, человеку, который будет смотреть твой код совсем непонятно, что лежит в этой переменной, также тут как то не совсем верно написала jsx должно быть вот так:
```
         <div className={bgStyle.content}>
             {!state.hasError&&state.list && (
                 <BurgerIngredients data={state.list} />
                 <BurgerConstructor list={state.list} />
              )}
         </div>
```

2022-01-15 22:26 UTC, grishbar commented on src/components/appHeader/AppHeader.js
> +}
`надо исправить`
ты не совсем корректно пишешь jsx, попробуй самостоятельно посмотреть на примеры с [официального сайта reactа ](https://ru.reactjs.org/docs/introducing-jsx.html)
А лучше настрой линтер для этого запусти вот эту команду 
`npm i eslint-config-airbnb eslint-plugin-jsx-a11y --save-dev`
далее надо создать файлик `.eslintrc` в корне проекта и туда записать:
```
{
    "extends": [
      "react-app",
      "airbnb",
      "plugin:jsx-a11y/recommended"
    ],
    "plugins": [
      "jsx-a11y"
    ],
    "rules": {
      "semi": 0,
      "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", "tsx"] }]
    }
}
```
после этих действий у тебя в коде будет везде подсвечиваться некорректный синтаксис, сможешь исправить все ошибки и получится великолепный чистый код

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerConstructor/BurgerConstr.js
> +        isLocked={isLocked}
`можно лучше`
можно просто isLocked

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerConstructor/BurgerConstr.js
> +  const [show, setShow] = useState(false);
`надо исправить`
булевые переменные должны начинаться с артикля, например isModalVisisble

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerConstructor/BurgerConstr.js
> +            console.log("Close it!");
`надо исправить`
удали пожалуйста console.log во всем проекте

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerConstructor/BurgerConstr.js
> +          }}}>
`надо исправить`
Во первых [нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)
Во вторых ты должна добавить подписку на событие клика клавиш и там отлавливать нажатие клавиши escape, и также не забудь добавить отписку от этого события при размонтировании компонента

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerIngredients/BurgerIngredients.js
> +          }}}>
`надо исправить`
тут тоже самое убрать создание функций из jsx и добавить обработку клавиши через useEffect

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerIngredients/BurgerIngredients.js
> +          <h1 id='three'>Начинки</h1>
`надо исправить`
у тебя каждый блок хранит ингредиенты определенного типа, назови id соответственно этим типам

2022-01-15 22:26 UTC, grishbar commented on src/components/burgerIngredients/SubTub.js
> +    <div style={{ display: 'flex' }}>
`надо исправить`
инлайновые стили это очень плохая практика, старайся без очень сильной необходимости неиспользовать их, вот [здесь](https://htmlacademy.ru/blog/boost/frontend/inline) есть статься про это

2022-01-15 22:26 UTC, grishbar commented on src/components/modalOverlay/Modal.js
> +  })
`надо исправить`
избавься от манипулирования с домом напрямую, тебе надо в app.js или в index.js добавить div для модалки, и тут его селектить не более того

2022-01-16 10:59 UTC, Yodiculta commented on src/components/burgerConstructor/BurgerConstr.js
> +        isLocked={isLocked}
Если просто isLocked, то все становится isLocked, а должны только 1 и последний элементы.
Еще вопросик насчет kebab-case, как я погуглила, это типа calculate-elephant-weight, неужели все компоненты надо в такое переименовать? burger-ingredients, app-header, burger-constructor? Мне кажется, я такого не видела ни в тз ни в тренажере

2022-01-16 11:43 UTC, Yodiculta commented on src/components/burgerIngredients/BurgerIngredients.js
> +          }}}>
у меня ведь прописан EventListener("keydown", escFunction) в компоненте Modal, как-то не совсем понятно что не так(((

2022-01-16 11:51 UTC, Yodiculta commented
UseEffect с подпиской на нажатие Esc прописан в компоненте Modal, остальное, вроде как, пофиксила, большое спасибо!
Проверьте, пожалуйста, еще раз

2022-01-16 15:25 UTC, grishbar requested changes
Отлично, большую часть проблем исправила, осталось еще немного:

- [ ] Исправить все eslint ошибки 
- [ ] Поправить работу с оверлеем для модалки

2022-01-16 15:25 UTC, grishbar commented on .eslintrc.json
> +{
`надо исправить`
круто, что добавила eslint, но теперь надо бы все ошибки иправить иначе приложение не запускается
![Screen Shot 2022-01-16 at 18 07 02](https://user-images.githubusercontent.com/32193933/149665677-5e107341-e7f6-43ec-a48a-b306a85ad8e0.png)

2022-01-16 15:25 UTC, grishbar commented on src/components/app/App.tsx
> +const COSMO_BURGERS_URL = 'https://norma.nomoreparties.space/api/ingredients'
`можно лучше`
это скорее INGREDIENTS_URL

2022-01-16 15:25 UTC, grishbar commented on src/components/app/App.tsx
> +      <div id="modal-overlay" />
`надо исправить`
у тебя тут не должно быть div для оверлея модалки, особенно, когда рядом нет самой модалки, совсем непонятно откуда тут этот див взялся весь оверлей должен быть описан внутри компонента модалки

2022-01-16 15:25 UTC, grishbar commented on src/components/burgerConstructor/BurgerConstr.jsx
> +  productDetails, type, isLocked, flag, name,
`надо исправить`
не очень понятно, что такое flag, старайся давать осмсленные название, такие, что не читая код можно было примерно представить, что лежит в твоей переменной

2022-01-16 15:25 UTC, grishbar commented on src/components/burgerIngredients/BurgerIngredients.jsx
> +            }
`можно лучше`
можно задизейблить правило no-underscore-dangle сразу для всего файла, чтобы не дизейблить его постоянно, для этого на первой строчке надо написать:
```
/* eslint-disable no-underscore-dangle */
```

2022-01-16 15:30 UTC, grishbar commented on src/components/burgerConstructor/BurgerConstr.js
> +        isLocked={isLocked}
Да, ты права показалось, что у тебя тут isLocked={true} написано, поэтому так написал, оставляй как есть

2022-01-16 20:14 UTC, grishbar commented
Что то у тебя совсем поплыла верстка и шрифты пропали, поправь пожалуйста сделай в соответствии с макетом и приму работу
<img width="1429" alt="Screen Shot 2022-01-16 at 23 13 51" src="https://user-images.githubusercontent.com/32193933/149676373-d52130bb-625b-4be7-bb5a-0f9f7006062e.png">

2022-01-16 21:29 UTC, Yodiculta commented
Что не так? я использую шрифт JetBrains как в фигме.

Добавила отступ слева для меню вверху. Нам говорили, что использование отступов из вашей библиотеки не является обязательным для прохождения ревью (я сначала не могла ее поставить, поэтому сделала без нее). Это не так?

2022-01-16 22:33 UTC, grishbar commented
Тут не хочется требовать пиксель перфект верстку, так как мы все таки изучаем реакт, но прям заметные проблемы в верстке должны быть исправлены:

- [ ] Должен использоваться шрифт "JetBrains Mono", как в макете
- [ ] Посмотри внимательно на хэдер у него не должно быть никаких отступов и он должен быть растянут на всю ширину экрана + расположение элементов в хэдере совсем не похоже на то как в макете
- [ ] Обрати внимание на табы в меню ингриденов как они расположены у тебя и как на макете
- [ ] Обрати внимание на кнопку оформить заказ и на сумму с иконкой около нее, тут тоже есть различия

Это основоные, которые сильно бросаются в глаза, их надо исправить для принятия работы, будет хорошо если сама найдешь все мелкие разногласия и поправишь тоже, но это уже необязательно.
Можешь скачать [плагин PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=ru), скачать картинку с макета и наложить на твой сайт, так сразу станут заметны все проблемы.

2022-01-17 17:48 UTC, Yodiculta commented
Проверьте, пожалуйста, снова.
Извините, что так много попыток)

2022-01-18 00:07 UTC, grishbar requested changes
Надо еще поправить несколько моментов:

Шрифты все еще отличаются опиши шрифты в index.css аналогично другим, чтобы все заработало
Модалка с деталями ингридиента совсем не похожа на то, что в макете, также при клике на modal-overlay модалка не закрывается, хотя должна, аналогично для модалки деталей заказа
 
![Screen Shot 2022-01-18 at 03 05 05](https://user-images.githubusercontent.com/32193933/149849643-309253fb-68eb-4533-b9c0-b13a910d45f8.png)

2022-01-18 00:07 UTC, grishbar commented on .eslintrc.json
> +    "linebreak-style": 0
`надо исправить`
ты тут неправильно написала правило, оно должно быть внутри объекта rules
```
    "rules": {
      "semi": 0,
      "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", "tsx"] }],
      "linebreak-style": 0
    }
```

2022-01-18 00:07 UTC, grishbar commented on package.json
> +    "json-loader": "^0.5.7",
`надо исправить`
что это за библиотеки, кажется их нигде не используешь, надо удалить если не нужны

2022-01-18 00:07 UTC, grishbar commented on src/components/appHeader/AppHeader.module.css
> +  font-family: 'JetBrains Mono', Arial, sans-serif;
`надо исправить`
недостаточно просто написать шрифт, его еще нужно описать в index.css аналогично другим шрифтам а еще лучше, в отдельный файл описание шрифтов вынести например в fonts.css

2022-01-18 00:07 UTC, grishbar commented on src/components/burgerIngredients/BurgerStyle.module.css
> +}
`можно лучше`
как то поехали у тебя тут отступы в css старайся соблюдать корректную идентацию, тут также можешь настроить [stylelint](https://stylelint.io/) чтобы у тебя подсвечивался некорректный синтаксис

2022-01-18 18:16 UTC, Yodiculta commented
Проверьте, пожалуйста, снова

2022-01-19 00:17 UTC, grishbar requested changes
Проверяй пожалуйста работу перед отправкой, весь сайт поплыл, исправь пожалуйста
И избавься от создания функций внутри jsx
<img width="1421" alt="Screen Shot 2022-01-19 at 03 16 43" src="https://user-images.githubusercontent.com/32193933/150039599-dda16b0f-ff96-4de7-a5d3-8a4f9f20eb61.png">

2022-01-19 00:17 UTC, grishbar commented on src/components/burgerIngredients/BurgerIngredients.jsx
> +      onClick={() => onOpen(productDetails)}
`надо исправить`
Уже писал, повторюсь, [нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)

2022-01-19 19:11 UTC, grishbar commented
Хорошо, работу принимаю, удачи в дальнейшем обучении!)

2022-01-20 12:06 UTC, Yodiculta commented
Ого, спасибо) сори что я вас так мучала☻

2022-01-20 12:07 UTC, merged